name: keto_calculator
description: Nutrition tracking mobile app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.1.0
  cloud_firestore: ^6.1.1
  device_info_plus: ^12.3.0
  firebase_core: ^4.3.0
  firebase_storage: ^13.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  get_it: ^9.2.0
  http: ^1.6.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  meta: ^1.16.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.4
  uuid: ^4.5.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env

flutter_native_splash:
  android: true
  ios: true
  # android_gravity: fill
  # ios_content_mode: scaleAspectFill
  color: "#657064"
  image: assets/images/splash_source.png
  android_12:
    image: assets/images/splash_source.png
    color: "#657064"    
